spring:
  application:
    name: @project.name@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://${USERSDB_CONTAINER_NAME:localhost}:${USERSDB_PORT:3306}/${USERSDB_NAME:usersdb}?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${USERSDB_USER:root}
    password: ${USERSDB_PASSWORD:Pa$$w0rd}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8100

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}